project:
  type: book
number-sections: true
number-depth: 4
csl: medical_physics.csl
lang: es
link-citations: true
execute:
  echo: false
jupyter: python3
book:
  favicon: logouni.png
  title: Soluciones para la reconstrucción de aplicadores ginecológicos en braquiterapia sobre MRI
  author: 
    - name: "Antonio Otal Palacín"
      orcid: "0000-0003-2704-7995"
  date-format: "MMMM YYYY"
  date: Marzo 2024
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - abstract.qmd
    - siglas.qmd
    - introduction.qmd
    - m&m.qmd
    - results.qmd
    - discusion.qmd
    - conclusions.qmd
    - references.qmd
  
bibliography: referencias.bib
format:
  html:
    cover-image: logouni.png
    theme:
      - cosmo
  pdf:
    documentclass: scrbook
    pdf-engine: xelatex
    fontsize: 12pt
    interlinespace: 1.5
    link-bibliography: true
    link-citations: true
    lof: true
    lot: true
    template-partials:
      - before-body.tex
      - dedication.tex
    geometry:
      - paperwidth=17cm
      - paperheight=24cm
      - top=35mm
      - left=20mm
      - right=20mm
      - bottom=35mm
      - headsep=10mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
      - pdfwindowui
      - pdfview=FitBH
      - pdfstartview=FitB
    include-in-header: 
      text: |
            \usepackage{ragged2e}
            \usepackage{tocbibind}
            \usepackage{graphicx}
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            \fancyhf{} % Limpiar todos los campos de encabezado y pie de página
            \renewcommand{\chaptermark}[1]{\markboth{\MakeUppercase{#1}}{}}
            \renewcommand{\headrulewidth}{1pt} % Eliminar la línea de separación del encabezado % Configuración del encabezado izquierdo con la imagen
            \fancyhead[R]{\vfill \leftmark}
            \cfoot{\thepage}            


  docx:
    reference-doc: val.docx
    toc: true
  epub:
    toc: true