project:
  type: book
number-sections: true
number-depth: 4
csl: medical_physics.csl
lang: es
link-citations: true
execute:
  echo: false
jupyter: python3
book:
  title: Soluciones de reconstrucción mediante RMN
  author: Antonio Otal Palacín
  chapters:
    - index.qmd
    - introduction.qmd
    - m&m.qmd
    - results.qmd
    - papers.qmd
    - discusion.qmd
    - references.qmd
bibliography: referencias.bib
format:
  html:
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt
  docx:
    reference-doc: val.docx
  epub:
    toc: true