project:
  type: book
number-sections: true
number-depth: 4
csl: medical_physics.csl
lang: es
link-citations: true
execute:
  echo: false
jupyter: python3
book:
  favicon: LogoUni.png
  title: Soluciones de reconstrucción mediante MRI
  author: Antonio Otal Palacín
  chapters:
    - siglas.qmd
    - index.qmd
    - introduction.qmd
    - m&m.qmd
    - results.qmd
    - papers.qmd
    - discusion.qmd
    - conclusions.qmd
    - references.qmd
bibliography: referencias.bib
format:
  html:
    cover-image: LogoUni.png
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt
    lof: true
    lot: true
    geometry:
      - top=30mm
      - bottom=25mm
    include-in-header: 
      text: |
            \usepackage{tocbibind}
            \usepackage{graphicx}
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            \fancyhf{} % Limpiar todos los campos de encabezado y pie de página
            \renewcommand{\chaptermark}[1]{\markboth{\MakeUppercase{#1}}{}}
            \renewcommand{\headrulewidth}{1pt} % Eliminar la línea de separación del encabezado % Configuración del encabezado izquierdo con la imagen
            \fancyhead[L]{\vfill \includegraphics[width=3cm]{header_s.png}}
            \fancyhead[R]{\vfill \leftmark}
            \cfoot{\includegraphics[width=20cm]{footer.png}}


  docx:
    reference-doc: val.docx
    toc: true
  epub:
    toc: true