project:
  type: book
number-sections: true
number-depth: 4
csl: medical_physics.csl
lang: es
link-citations: true
execute:
  echo: false
jupyter: python3
book:
  favicon: logouni.png
  title: Soluciones de reconstrucción mediante MRI
  subtitle: A ver si ahora sí
  author: 
    - name: "Antonio Otal Palacín"
    - orcid: "0000-0002-4677-535X"
  date: "01 June 2026"
  date-format: "MMMM YYYY"
  chapters:
    - siglas.qmd
    - index.qmd
    - introduction.qmd
    - m&m.qmd
    - results.qmd
    - papers.qmd
    - discusion.qmd
    - conclusions.qmd
    - references.qmd
bibliography: referencias.bib
format:
  html:
    cover-image: LogoUni.png
    theme:
      - cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    link-bibliography: true
    link-citations: true
    lof: true
    lot: true
    template-partials:
      - before-body.tex
    geometry:
      - top=35mm
      - bottom=35mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
      - pdfwindowui
      - pdfview=FitBH
      - pdfstartview=FitB
    include-in-header: 
      text: |
            \usepackage{tocbibind}
            \usepackage{graphicx}
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            \fancyhf{} % Limpiar todos los campos de encabezado y pie de página
            \renewcommand{\chaptermark}[1]{\markboth{\MakeUppercase{#1}}{}}
            \renewcommand{\headrulewidth}{1pt} % Eliminar la línea de separación del encabezado % Configuración del encabezado izquierdo con la imagen
            \fancyhead[L]{\vfill \includegraphics[width=3cm]{header_s.png}}
            \fancyhead[R]{\vfill \leftmark}
            \lfoot{\includegraphics[width=15cm]{footer.png}}
            \rfoot{\thepage}


  docx:
    reference-doc: val.docx
    toc: true
  epub:
    toc: true