# Agradecimientos {.unnumbered}

Mucho tiempo ha pasado desde finales de 2016, fecha en que comenzó este trabajo y ha sido tanta la gente que ha colaborado directa o indirectamente en él que seguramente hará que me olvide de algunos. Por eso, gracias a todos y disculpas a los que me deje en el tintero.

En primer lugar, quiero agradecer a mis directores de tesis, el Dr. José Pérez Calatayud y el Prof. Javier Vijande Asenjo la paciencia y los ánimos para continuar que nunca han dejado de regalarme durante este viaje. Sus valiosísimos consejos y su guía son los elementos en los que se sostiene la investigación presentada.         

Quiero expresar mi gratitud a los co-autores firmantes de los artículos derivados de esta investigación por su colaboración y esfuerzo conjunto en la producción de dichas publicaciones.

Quiero dar las gracias a los desarrolladores de software y hardware libre por su inestimable y desinteresada ayuda y en especial al Dr. Juan González Gómez, más conocido en la red como Obijuan. El descubrimiento de sus tutoriales de FreeCAD supusieron un antes y un después en el desarrollo de este proyecto.   

Gracias al personal del servicio de Radiofísica y Protección Radiológica del Complejo Hospitalario de Navarra por todo lo mucho que aprendí allí durante mi residencia y por el cariño con el que me trataron. En especial quiero agradecer a Santiago Pellejero Pellejero todo lo que aprendí de él sobre braquiterapia. Sin ese bagaje nada de esto hubiese comenzado.

Gracias a mis compañeros de la Clínica Benidorm, en especial a la Dra. Silvia Rodríguez Villalba al Dr. Manuel Santos Ortega y a José Richart Sancho. A su lado fue como arrancó, tomó forma y se consolidó la investigación que se presenta.

Muchas gracias a todos mis compañeros de mi actual lugar de trabajo, el Servei de Protecció Radiologica i Radiofisica del Hospital Universitari Arnau de Vilanova de Lleida por integrarme en su grupo desde el primer día. Gracias a mis compañeras radiofísicas, Carlota Monfà Binefa y Meritxell Visus Llobet, por el poder trabajar con personas de su valía todos los días. También a Àngel Forner Forner que, aunque ya no trabaja con nosotros, siempre será del equipo. Gracias al Dr. Óscar Ripol Valentín por su ilusión en cada proyecto que empezamos.

Agradezco también mucho a el Dr. Sergio Alberto Lozares Cordero y al Prof. Facundo Ballester Pallarés el que me animasen cada uno por su lado a tomar la decisión de ejercer la profesión de radiofísico hospitalario.

Un recuerdo muy especial a mis padres, Sole y Jesús. Lamento mucho que no hayan podido compartir conmigo el momento de presentar el presente trabajo y estoy seguro de que hubiesen disfrutado mucho de verme concluir este trabajo.

Y sobre todo quiero dar las gracias a mis dos hijos, Lorenzo y Leonardo, por ser como son y sorprenderme todos los días. Y a Ascen, la luz que siempre brilla a mi lado.    


