# Conclusiones

Si partimos del hecho de que la MRI es la modalidad de imagen óptima para el tratamiento mediante BT del carcinoma de cérvix avanzado, la reconstrucción exclusiva sobre MRI de aplicadores ginecológicos es una alternativa robusta a la basada en registro de imágenes con CT. Es evidente la reducción de las incertidumbres asociadas a la reconstrucción exclusiva al eliminar las introducidas por los procedimientos de registro de CT-MRI. Por otro lado, es innegable que la peor visibilidad de los aplicadores ginecológicos en MRI, especialmente de la parte intersticial, hace que la reconstrucción sobre dicha modalidad de imagen introduzca nuevos retos. Dichos retos pueden ser superados utilizando técnicas basadas en bibliotecas de aplicadores.    

La reconstrucción de aplicadores intra-cavitarios mediante el uso de bibliotecas de aplicadores se revela como una herramienta versátil que puede extenderse a aplicadores que, aunque no sean estrictamente rígidos, pueden configurarse como tales, adaptándose a la disposición específica de cada implante. De esta manera al obtener un modelo de aplicador configurado para un implante específico, no es necesario ver explícitamente sobre la MRI los canales por donde circula la fuente, siempre que haya otras partes visibles del aplicador sobre la imagen, aunque estas sean periféricas. Más importante todavía es que un punto tan crítico como es la *tip-position* de cada canal puede ser determinado gracias a la configuración conocida del aplicador. En el concepto de aplicadores que no sean estrictamente rígidos podemos incluir la parte intersticial aprovechando los puntos comunes de dicha parte con la compartida con la intra-cavitaria y la medida de la profundidad de inserción. 

Aprovechando las técnicas descritas en el párrafo anterior donde definimos un modelo de aplicador completo para un implante determinado, podemos utilizar un modelo de este tipo sobre una imagen pre-implante y optimizar la dosimetría previamente al implante real. Las bibliotecas de aplicadores utilizando el concepto anterior permiten la creación de planes virtuales basados en imágenes previas al procedimiento intervencionista. Este enfoque permite probar diferentes configuraciones de la parte intersticial del aplicador buscando la que en opinión del médico intervencionista sea la que resulte en un mejor compromiso de cobertura de los volúmenes blanco y de la protección de los OAR. Estos planes virtuales serían análogos a los utilizados con el mismo fin en braquiterapia de próstata.

Las peculiaridades de la BT de cérvix basada exclusivamente en MRI exige dotar de nuevas herramientas a los TPS con el objeto de ayudar a los profesionales a crear tratamientos cada vez mejores que redunden en la calidad de los tratamientos. Es de vital importancia que las casas comerciales que desarrollan y comercializan los TPS tomen en cuenta las sugerencias y las carencias señaladas por los MP y los ORT que realizan los implantes de braquiterapia, pudiendo ser las herramientas *caseras* desarrolladas por la comunidad de usuarios una fuente de inspiración. Nuevos avances como el seguimiento electromagnético o la explosión de herramientas basadas en inteligencia artificial cuyos resultados van desde la generación de CT sintéticos a partir de una MRI a la segmentación automática de volúmenes (o de aplicadores) pueden hacer evolucionar los TPS de braquiterapia en general y para el tratamiento exclusivo con MRI del cáncer de cérvix en particular.  
