# Discusión

## Artículo sobre librerías

Como se vio en la [sección @sec-bibapp], la reconstrucción basada en bibliotecas de aplicadores no es posible en el caso de la componente intersticial, ya que el aplicador completo puede no considerarse rígido[@hellebust2010]. Sin embargo, mediante la aplicación del método expuesto en la [sección @sec-MM-reconstruction] es factible el uso de las bibliotecas de aplicadores en la reconstrucción de agujas. Por lo tanto, en este trabajo presentamos un método para incluir aplicadores intersticiales en la biblioteca Oncentra TPS y describimos un método de reconstrucción con fines de planificación.

En el caso del aplicador Utrecht, la falta de maniquíes dificulta el ajuste de las agujas. La localización de las puntas de las agujas es esencial para determinar con precisión la distancia máxima entre la fuente y el indexador; sin embargo, la línea negra disponible en la RM T2 dificulta enormemente esta determinación. Antes del desarrollo de la biblioteca presentada en este trabajo, utilizábamos el siguiente procedimiento en la reconstrucción del aplicador de Utrecht: 1) las posiciones de los catéteres del tándem y del ovoide se determinaron a partir de la del maniquí salino existente; 2) las agujas se reconstruyeron utilizando la metodología descrita en Pérez-Calatayud et al. [@pérez-calatayud2011]. Brevemente, esto consistió en utilizar la información de profundidad de inserción, es decir, la profundidad desde la superficie del ovoide hasta la punta de la aguja, proporcionada por el oncólogo radioterapeuta. A continuación, se colocó en el plano reconstruido una regla de software ajustada a la profundidad de inserción y se utilizó para definir los diferentes puntos del catéter, incluidas las puntas de las agujas. Como se ha indicado anteriormente [@pérez-calatayud2011], la profundidad de inserción reproducida mediante la regla del programa informático corresponde a la distancia desde la superficie del ovoide, pero con un desplazamiento de -0,7 cm, para tener en cuenta la distancia máxima entre la fuente y el indexador de 129 cm en el cargador posterior (microSelectron, versión 2 o 3 de Elekta). Este procedimiento es laborioso e implica cierta incertidumbre en el ajuste del punto de salida de la aguja del ovoide, junto con la suposición de que la aguja es perfectamente recta.

En nuestra opinión, el uso de la biblioteca que hemos desarrollado mejora significativamente la eficacia. En primer lugar, se puede seleccionar un aplicador virtual en función de las profundidades de la aguja; el tándem y los ovoides se pueden establecer rápidamente porque la estructura rígida del aplicador permite utilizar maniquíes y cursivas del aplicador. Una vez establecidos los ovoides, se pueden obtener los puntos de salida de las agujas y sólo se necesitan ligeras correcciones para ajustar su posición en función de su vacío de señal en los límites de la punta.

Para evaluar la mejora de la precisión, se han utilizado ambos métodos de reconstrucción en tres planos diferentes. Uno de los beneficios del nuevo método propuesto se evidencia con la determinación más precisa de la punta para ambos catéteres, tándem y ovoide, mejorando la incertidumbre de 2 mm debida al efecto de volumen parcial por el grosor del corte de RM. En el caso de las agujas, el método propuesto reduce las incertidumbres previas de unos 2 mm en el punto de salida del ovoide, y hasta 5 mm en la punta de la aguja. Las mayores desviaciones en la determinación de la punta de la aguja se deben a la suposición de agujas perfectamente rectas. Utilizando la biblioteca desarrollada, también es posible mezclar la aguja virtual para que se ajuste mejor a las trayectorias curvas de la real.

En el caso de la TB, que utiliza agujas de titanio, la reconstrucción puede basarse normalmente en los artefactos de aguja que pueden verse en las secuencias de RM T1, utilizando el vacío en la punta como posición de la punta de la aguja. Sin embargo, los tejidos que rodean las agujas pueden presentar heterogeneidades que complican la identificación precisa de estos patrones de artefactos, y esta dificultad es más pronunciada en las secuencias T2, que es la secuencia preferida para el contorneado.

Con el nuevo método presentado aquí, el tiempo necesario para identificar las posiciones de las agujas se reduce considerablemente, al menos hasta un 50%. El aplicador virtual con la profundidad de aguja requerida se selecciona en Oncentra y, utilizando los tres gránulos de vitamina A como guías, se fija en el estudio de imagen T2 de RMN. A continuación, cada orientación de la aguja se establece utilizando sólo una imagen de plano axial, en la que el vacío en la punta de la aguja de titanio es claramente visible con un buen contraste. Típicamente, sólo dos planos axiales son suficientes para fijar todas las agujas. Las ventajas de este enfoque para la TB son el ahorro de tiempo (lo estimamos en al menos alrededor del 50%, promediando el tiempo beneficiado en diferentes casos y diferentes físicos) y la reducción de la probabilidad de identificación errónea del catéter, que puede ser un problema debido al gran número de agujas que se suelen utilizar en la práctica clínica (mínimo 14 agujas).

El método aquí propuesto es específico para el Oncentra TPS, y también para los aplicadores Elekta Utrecht y TB. Sin embargo, puede adaptarse a otros aplicadores TPS e intersticiales teniendo en cuenta la gestión específica de su biblioteca de aplicadores. Por ejemplo, esta metodología se está desarrollando actualmente también para el TPS Sagiplan (Eckert & Ziegler, Bebig, Alemania). En Sagiplan, existe un conjunto de piezas (llamadas cursivas), con las que componemos los aplicadores (llamados cursivas). Dentro de cada configuración de cluster, obtenemos la posición relativa entre todas las piezas que conforman ese cluster. Así, en un ejemplo de aplicador con una pieza intersticial, como el aplicador Viena [@kirisits2006a], con un modelo 3D con los puntos de salida de las agujas perfectamente determinados, podríamos configurar un sistema similar al descrito anteriormente.

## Pre-plan

La aplicación Java desarrollada presenta una interfaz de usuario amigable, como se muestra en la Figura 2. El usuario puede seleccionar eficientemente las agujas (tanto rectas como divergentes) a incluir junto con la longitud libre, y a continuación su profundidad. Esta información se incorpora automáticamente a la biblioteca de aplicadores. La RM previa a la braquiterapia se realiza en modo T2, que es el recomendado para el contorneado. Una vez seleccionado el número virtual específico de agujas y profundidades, se realiza un plan virtual en Oncentra TPS y se optimiza según la dosimetría requerida y la cobertura del CTV, la "densidad" de agujas (distancia entre agujas) y la extensión. La figura 3 muestra un caso de pre-plan virtual de RMN y planificación de RMN para dosimetría. En el plan virtual, la plantilla se reconstruye utilizando la biblioteca según Otal et al. [@otalMethodIncorporateInterstitial2017a]. En la figura 4 se muestra una vista renderizada de un ejemplo de plan virtual, en la que se ilustran los gránulos de vitamina A (A1-A3), las agujas y el tándem uterino.

El procedimiento de preplanificación virtual presenta ventajas significativas: estimación de la profundidad de las agujas, posición y número de las mismas, optimización de la cobertura del CTV y minimización de las dosis en los órganos de riesgo. "Un implante subóptimo nunca puede transformarse en una aplicación satisfactoria mediante ninguna forma de optimización de la planificación del tratamiento" [@gecestrohandbook2002]. Las correcciones son limitadas en los casos de una dosimetría subóptima debida a un volumen de tratamiento no cubierto. La planificación del tratamiento basada exclusivamente en RM es preferible a otras modalidades de imagen empleadas tradicionalmente, como la TC o los métodos que combinan RM y TC. Las incertidumbres se reducen con la RM exclusiva debido a las imprecisiones derivadas de los procedimientos de registro TC-RM[@hellebust2010]. En consecuencia, ha crecido el interés por desarrollar dispositivos totalmente compatibles con la RM que permitan la inserción y el guiado en tiempo real de los aplicadores de braquiterapia[@viswanathan2006] . Otra opción es el pre-plan de RM. La principal limitación del pre-plan es la falta de un componente intrauterino/intracavitario y la probabilidad de divergencia de las agujas, sobre todo cuando no se utilizan agujas rígidas. La posición del útero varía en la mayoría de las pacientes, siendo recto tras la inserción de la sonda intrauterina. El pre-plan puede realizarse con componente IC bajo anestesia general [@fokdal2013] o paravaginal [@petric2014c]. A pesar de un pre-plan virtual, estos autores describen un sexto de todas las agujas planificadas, e implantadas como agujas libres debido a la limitación geométrica del tándem/anillo y del aplicador de agujas [@fokdal2013]. Las plantillas perineales como la TB evitan las limitaciones anteriores debidas al uso de agujas rígidas, pueden añadir un componente intrauterino y pueden cubrir todas las direcciones de extensión del tumor.

Este procedimiento de planificación previa se ha aplicado con éxito en 10 pacientes consecutivas. Se ha logrado una excelente reproducción de la planificación previa virtual. Cuando se trata a pacientes histerectomizadas, sólo hay un pequeño cambio del pre-plan al post-plan. Según nuestra experiencia, en pacientes sin cirugía, los cambios de agujas también son pequeños, tanto en número como en posición tras la inserción (dentro de 5 mm en la punta para una profundidad típica de 160 mm). El mismo oncólogo radioterapeuta experimentado (SR) ha realizado el contorneado tanto en la RM previa a la braquiterapia como en la RM posterior al implante. En nuestra opinión, esta técnica de pre-planificación virtual puede extenderse fácilmente a otros aplicadores multi-intersticiales como MUPIT o Syed, con un número optimizado de agujas y una profundidad adecuada. La planificación previa y la biblioteca permiten un implante fácil y una reconstrucción rápida que es segura y ahorra tiempo.

## Cancers

El principal objetivo de este estudio es proponer mejoras y señalar las lagunas de los TPS existentes. Se excluyeron del estudio los programas informáticos externos compatibles con los TPS que podrían ayudar a mejorar los problemas aquí señalados, incluidos los entornos de scripting dentro de los TPS que pueden permitir al usuario programar herramientas personalizadas. Como se ha comentado anteriormente, esta revisión se basa en la experiencia clínica de un grupo de oncólogos radioterapeutas y físicos médicos. También se utilizaron demostraciones interactivas proporcionadas por los fabricantes de software e impartidas por especialistas de las empresas proveedoras. Se pidió a estos especialistas que propusieran soluciones a algunos de los retos mediante un cuestionario. Las posibles limitaciones de esta metodología son las siguientes. Se basa en la opinión de expertos y especialistas, por lo que los sesgos personales son siempre un riesgo. En este caso, teniendo en cuenta que se trata de un grupo relativamente grande de profesionales que trabajan en diferentes instituciones (diferentes protocolos, instalaciones, formación, etc.), este problema es menor. Otra posible limitación es el hecho de que no todos los expertos hayan utilizado todos los TPS en su práctica clínica, algo inevitable teniendo en cuenta las realidades de la práctica clínica. El uso de cuestionarios también podría limitar el estudio, ya que intrínsecamente tienen sesgos de selección y muestreo que podrían impedir el descubrimiento de situaciones imprevistas.

Además, este modesto estudio multicéntrico y multidisciplinar tiene como objetivo fundamental señalar deficiencias y limitaciones, más que cuantificar sus consecuencias.

Existe un software de segmentación que incorpora herramientas más avanzadas para el registro de imágenes que incluyen utilidades para la suma de dosis entre diferentes fracciones. Sería deseable que estas herramientas, o similares, acabaran llegando a los TPS.

Otras herramientas, esta vez relacionadas con la segmentación de volúmenes clínicos y órganos en riesgo, que sería interesante incorporar a los TPS específicos de braquiterapia automatizarían dicha segmentación mediante redes neuronales convolucionales. Éstas ya se están incorporando al flujo de trabajo clínico en radioterapia, y existen trabajos recientes en la literatura orientados explícitamente al caso del cérvix [@ma2021; @shi2021; @wang2020], aunque la TC es la modalidad de imagen utilizada en estos trabajos.

Un tema apasionante en radioterapia externa es la generación de TC sintéticas a partir de RM. El objetivo principal de la generación de estos TC es segmentar los tumores y órganos de riesgo en la RM y obtener las densidades electrónicas necesarias para el cálculo de la dosis [@boulanger2021]. Estas TC sintéticas podrían ser útiles en el caso de la braquiterapia cervical y constituyen hoy en día una línea de investigación inexplorada. La comunidad de usuarios ha desarrollado históricamente herramientas "internas" que intentan compensar las deficiencias de los TPS y que normalmente no pueden incorporarse al flujo de trabajo del planificador. Un ejemplo comúnmente conocido son las hojas de cálculo. Un entorno de scripting robusto en un lenguaje de alto nivel ayudaría a los usuarios a optimizar sus rutinas de trabajo y también sería una fuente de inspiración para las empresas que integren el desarrollo de futuros productos.

En los últimos años, varios grupos de investigación han estado trabajando en sistemas de seguimiento electromagnético [@beld2018;@beld2018;@bert2016;@vanheerden2021] para comprobar la trayectoria de la fuente de braquiterapia antes de la administración del tratamiento. Uno de los especialistas participa en un proyecto relacionado con dicha tecnología. Aunque su finalidad principal es verificar la trayectoria seguida, en el futuro podría utilizarse como herramienta de autorreconstrucción. En la actualidad, no está a disposición de los usuarios.

Recientemente se han publicado algunos estudios que investigan la viabilidad de algoritmos basados en aprendizaje profundo para la reconstrucción semiautomatizada de catéteres intersticiales durante la HDR ginecológica basada en RM [@shaaer2021].