# Índice de abreviaturas {.unnumbered}

| Acrónimo | Texto                                               |
|----------|------------------------------------------------------|
| AAPM     | *American association of physicist in medicine*      |
| ABS      | *American Brachytherapy Society*                       |
| BT       | *Brachytherapy*                                      |
| CT       | *Computed Tomography*                             |
| CTV      | *Clinical target volume*                               |
| CTV-HR   | *High risk Clinical target volume*                |
| CTV-IR   | *Intermediate risk Clinical target volume*            |
| DVH      | *Dose-volume histogram*                             |
| EBRT     | *External beam radiation therapy*                       |
| EMBRACE  | *Image guided intensity modulated External beam radiotherapy and MRI adaptative BRAchytherapy in locally advanced Cervical cancer* |
| EQD2     | *Equivalent total doses in 2-Gy fractions*                  |
| ESTRO    | *European Society for Therapeutic Radiation and Oncology* |
| FDG      | *Fluorine-18 Fluorodeoxyglucose*                             |
| GEC      | *Groupe Europeen de Curietherapie*                     |
| GTV      | *Gross tumor volume*                         |
| GWG      | *Gynecologic working group*                            |
| HDR      | *High dose rate brachytherapy*                  |
| HPV      | *Human papillomavirus*                            |
| ICRU     | *International Commission on Radiation Units and Measurements* |
| IGABT    | *Image-guided adaptive brachytherapy*         |
| IMRT     | *Intensity-modulated radiation therapy*                  |
| IROC     | *Imaging and radiation oncology core*                |
| MBDCA    | *Model-based dose calculation algorithms*              |
| MR       | *Magnetic resonance*                         |
| MRI      | *Magnetic resonance imaging*              |
| MUPIT    | *A multiple-site perineal applicator*                  |
| OAR      | *Organ at risk*                                    |
| PDR      | *Pulsed dose rate brachytherapy*                       |
| PET/CT   | *Positron-Emission Tomography/Computed Tomography* |
| PTV      | *Planning Target Volume*                       |
| RAL      | *Remote afterloader*               |
| RF       | *Radio frecuency*                                     |
| SBRT     | *Stereotactic Body Radiation Therapy*                 |
| TG       | *Task group*                                     |
| TPS      | *Treatment planning system*             |
| WG-DCAB  | *Working Group on Model-Based Dose Calculation Algorithms in Brachytherapy* |
| xml      | *Extensible Markup Language*                           |

{{< pagebreak >}}
