## Intro Cancers

In the last few decades, brachytherapy (BT, Interventional Radiotherapy, IRT) has been one of the cornerstones for the treatment of gynaecological lesions, being one of the most widely used, and successful, therapeutic techniques to be considered in these cases. Within gynaecological BT, cervix treatments have experienced the greatest development in recent years. Numerous authors have reported that intracavitary BT plays an essential role in the curative intent of locally advanced cervical cancer management, for which the conventional approach involves external beam radiotherapy (EBRT) with concurrent chemotherapy, followed by BT. Excellent local control rates are achieved with this scheme, as it has been demonstrated by different studies on the curative intent of locally advanced cervical cancer [1–3].

In the past decades, the development of new EBRT techniques, such as Intensity Modulated Radiotherapy (IMRT), Volumetric Modulated Arc Therapy (VMAT), Stereotactic Body Radiotherapy (SBRT), or Proton therapy (PT), have broadened the choices of a treatment scheme. In fact, the data of BT use in cervical cancer in the United States (USA) published by Han et al. [4] revealed a trend towards exclusive EBRT treatments, with a decrease in cause-specific survival and overall survival when BT was not employed. In 2013, Tanderup et al. [5] stated that, based on the data collected, exclusive EBRT treatments were not an option when the maximum survival was sought. In the same line, a recent joint publication of the Society of Gynaecologic Oncology (SGO) and the American Brachytherapy Society (ABS) concluded that “conformal external beam therapies such as IMRT or SBRT should not be used as alternatives to brachytherapy in patients undergoing primary curative-intent radiation therapy for cervical cancer” [6]. The National Comprehensive Cancer Network (NCCN) [7] also indicated that, with respect to cervical cancer, SBRT is not considered as an appropriate routine alternative to brachytherapy.

The gynaecological working group of the GEC ESTRO (GYN GEC-ESTRO), formed in the year 2000, is committed to move from 2D BT based on A points to 3D BT based on images, incorporating magnetic resonance imaging (MRI) in the BT planning of the cervix. A new concept of volume definition is proposed, taking into account the topography of the primary tumour at diagnosis and after response to radio-chemotherapy, as well as dosimetric aspects. GYN GEC-ESTRO published its first two recommendations in 2005 and 2006 [8,9], its nomenclature being universally adopted in 2006 [10]. The concept of image-guided adaptive BT (IGABT) thus arises, also called 4D BT, in which the CTV volumes are appropriate for the evolutionary response over time of each BT treatment (changes adjacent to the applicator due to tumour regression, oedema, or changes in organs at risk (OAR)) [11]. The results published at the time were scarce, and more scientific evidence was needed to support, with clinical and toxicity data, the safety of this novel and completely different way of planning the BT component when treating cervical carcinoma. To this end, the first large-scale prospective study on MRI-based cervix BT, EMBRACE I (International study on MRI-guided BRAchytherapy in Cervical cancer), was designed. The EMBRACE Collaborative Group published in 2010 and 2011 recommendations III and IV for the reconstruction of the applicators and image in IGABT [12,13]. Throughout these years, the number of publications with conclusive results have increased, both in single-institutional series [14–18], a multicentre retrospective study RetroEMBRACE (retrospective study of patients treated with IGABT based on CT or MRI before the beginning of EMBRACE [19]), and, recently, the definitive comprehensive data from EMBRACE I [20], with the consolidation of MRI-based IGABT for the treatment of cervical carcinoma. The recommendations of the GEC ESTRO (I–IV) have been used as a conceptual basis worldwide to introduce the IGABT, now being integrated into the current ICRU 89 [21].

Once adopting the use of MRI, it has been evidenced that the interstitial component added to the intracavitary one achieves a higher dose conformity and organs at risk sparing. It also allows the use of different combined applicators options depending on the manufacturer [22,23]. Prescription and reporting have also evolved from 2D, exclusively based on dose points (e.g., A points), to be focused nowadays on metrics based on Dose Volume Histograms (DVH) and the specific anatomy of the patient, as obtained from 3D images. GEC-ESTRO publications [8] introduced DVH metrics (D90, D2cc) for both prescription doses and constrains to OARs [24]. The most updated version of the GEC-ESTRO recommendations has been included in an ongoing prospective observational analysis, EMBRACE II [25]. The objective of that study is, on the one hand, the control of local, lymph node and systemic disease with decreased toxicity and, on the other hand, the definition of patients at risk (including translational research), effect of techniques of external radiotherapy, such as IMRT/VMAT, increased lymph node dose with integrated boost, and increased use of interstitial BT in IGABT.

Radical locally advanced cervical cancer treatment comprises pelvic EBRT with concomitant chemotherapy, following BT. The EBRT dose is usually 45–50 Gy in 1.8–2 Gy fractions. Lymph nodes, parametria, or pelvic sidewall boosts up to 55–64 Gy are used, depending on the clinical case and the experience of each individual centre [18,19]. Although HDR-BT schemes of 5.5–6 Gy × 5 fractions are recommended in some guidelines, the “nominal” 28 Gy in 4 fractions scheme is well-established thanks to the EMBRACE trials [26]. Usually, these four HDR-BT fractions are administered in two applications in 1–2 weeks, at the end of EBRT or intercalated between the last EBRT fractions. Overall treatment time, an independent prognostic factor for local control, should remain below 50–55 days [27].

As recommended by ICRU 89, the difference in the biological effects of the EBRT and BT fractions makes it necessary to define a parameter to evaluate them globally. The previously referenced publications make use of the dose equivalent of 2 Gy per fraction (EQD2), using the linear-quadratic model with α/β = 10 Gy for tumour effects and α/β = 3 Gy for late normal tissue damage, assuming a half-time repair time of 1.5 h. Therefore, following the ICRU 89 recommendations, EQD2 is the chosen option to sum the absorbed dose to report dose for planning aims, prescriptions, and delivered dose.

Clinical departments use external tools, such as the GEC-ESTRO spreadsheet, to calculate the resulted EQD2 for each patient. None of the current brachytherapy treatment planning systems (TPS) consider the fully CTV-OAR dose balance during the optimization, becoming a user-dependent procedure mostly based on the physicist experience.

Ideally, the reconstruction of the applicator geometry and its matching with the patient anatomy should be done in the same image study in which the radiation oncologist defines the CTV and OARs volumes in T2 weighted MRI. However, there is an important limitation to that technique when using dummies to identify the potential source trajectory for the interstitial component using plastic catheters. Namely, the void signal produced by the air-filled interior of the applicators makes it difficult to set the catheter tips. Therefore, the use of other image modalities is sometimes beneficial in the reconstruction process.

Therefore, the aim of this work is to review the different methodologies used by all commercially available TPSs to solve the main planning issues in an exclusive-MRI-based cervix BT with interstitial component treatment. Moreover, some desirable or convenient practical aspects to be implemented in future TPS versions are outlined from both radiation oncologist and medical physicist perspectives.


## Intro librerias

For cervical cancers, T2 magnetic resonance imaging (MRI) is the preferred image modality for image guided brachytherapy [1,2,3,4,5,6,7,8,9,10]. Traditionally, cervical cancer has been treated using only endocavitary applicators, i.e., uterine tandem plus ovoids/colpostats, or ring. Magnetic resonance imaging-guided brachytherapy has revealed the clinical target volume (CTV) coverage limits of these intracavitary applicators. In response, new applicators with interstitial components as well as the basic intracavitary applicator have been developed, e.g., the Vienna applicator (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden) [11], which uses plastic needles around the ring or the Utrecht applicator (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden) [12] with plastic needles on the ovoids.

For locally advanced cervical carcinoma with moderate extension to the parametrium, combined endocavitary and interstitial applicators are appropriate. Nevertheless, they cannot cover extensive disease affecting the distal vagina and/or parametrium. In these cases, interstitial treatments are recommended [6,13,14,15,16,17,18]. For instance, our institution has developed Template Benidorm (TB), a new combined endocavitary and interstitial applicator that is totally compatible with MRI [17]. Template Benidorm makes it possible to combine intracavitary brachytherapy with MRI-compatible transperineal interstitial needles. So, in our department, the Utrecht applicator or TB are selected depending on the lateral or vaginal extension of the disease. Treatment planning based exclusively on MRI is preferred to other traditionally employed image modalities [10]. Thus, the exclusive use of MRI for planning reduces reconstruction uncertainty, saving time, and increasing patient comfort.

Groupe Européen de Curiethérapie and European Society for Radiotherapy and Oncology (GEC-ESTRO) has published recommendations for commissioning and applicator reconstruction in MRI based treatment planning for cervix cancer brachytherapy [10], and contrasted the reconstruction issues involved with the use of MRI or computed tomography (CT). While the source channel is well visualized in CT images, applicator reconstruction is more challenging when using MRI images. Availability of commercial dummy sources for MRI is limited, and image artifacts may occur with titanium applicators.

One of the most important recent advances in the TPS (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden) has been the availability of the applicator library. It allows whole applicator reconstruction based on just a few anchor points, improving the accuracy, and it overcomes the lack of adequate MRI dummies. However, to our knowledge, no such library is currently available with the interstitial components of the Utrecht and the TB. Moreover, in these cases, the final applicator configuration is implant specific, since the needle arrangement is necessarily patient dependent.

The purpose of this work is to present a method to add the specific interstitial component to an existing TPS rigid library for the Utrecht and TB templates, thereby allowing more efficient reconstruction using only T2 MRI-based planning.

## Intro Pre-plan

The American Brachytherapy Society (ABS) together with the Groupe Européen de Curiethérapie and the European Society for Radiotherapy and Oncology (GECESTRO) have recommended magnetic resonance imaging (MRI) as the preferred image modality in image guided brachytherapy, specifically using the T2 acquisition sequence [1,2,3,4].

In locally advanced cervical carcinoma with moderate extension to the parametrium, combined endocavitary and interstitial applicators (Vienna [5] or Utrecht [6] applicators; Nucletron, Elekta AB, Stockholm, Sweden) are appropriate, although these have coverage limitations in patients with more advanced disease (distal parametrial affectation, medial or distal vaginal affectation, or extension to rectum or bowel), in which interstitial templates such as the Martinez universal perineal interstitial template (MUPIT) [7] (Nucletron, Elekta AB, Stockholm, Sweden) or the Syed template [8] (Best Medical International, Inc., Springfield, VA, USA) have been typically used. In an attempt to circumvent these difficulties, our department has developed a new gynecological applicator (Template Benidorm, TB) [9]. The device is a fully MRI-compatible applicator that engages titanium needles and an intrauterine tandem that allows the use of MRIbased dosimetry, thus providing the advantages of MRI volume definition. The use of MRI provide smaller and better defined target volumes, with statistically significant decrease of rectal toxicity, comparing with computed tomography (CT)-based treatments, as that is made using MUPIT template [10].

Pre-planning techniques are employed in external radiotherapy (EBRT), frequently in contrast with brachytherapy. Potential reasons of this, in addition to the lack of commercial applications in clinical routine, are the possible anatomic changes that are produced after the applicator insertion (uterus straighten).

To have a pre-plan is always desirable, because it is an important aid for achieving optimal implant geometry that is able to obtain the best dosimetry distribution and coverage of clinical target volume (CTV) in brachytherapy treatments. This is mainly in patients with cervix tumors with irregular volumes or poor responses to EBRT and chemotherapy. The advantages of use a pre-planning are evident, and any advance in this direction will have a significant benefit in clinical practice. This article presents the implementation of a pre-planning technique using the TB in multi-interstitial perineal and endocavitary gynecological brachytherapy.


