## Applicators, magnetic resonance imaging acquisition, and TPS

The Utrecht Interstitial CT/MRI Applicator Set (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden) has been specifically developed for combined intracavitary/ interstitial treatment of gynecologic cancers [12]. Its design is based on the Fletcher CT/MRI Applicator Set (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden), and it uses the ovoids as a template for interstitial needle placement (up to 4 plastic needles in each). The insertion depth of the needles can be controlled using insertion tool. The final needle set-up is implant dependent in both trajectory and depth. However, although there are dummies for the endocavitary component, there are none for the interstitial one. Currently, the needle positions are reconstructed using their black tunnel signal on T2 MRI and their insertion depth.

The TB (Lorca Marin, Murcia, Spain) consists of a template to allocate multiple Titanium needles and a cylinder, uterine tandem [17,18]. This template improves the existing MUPIT [14] template (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden) in that it implements both titanium needles and an intracavitary component, and is fully MRI compatible. The template consists of two perineal plates with two central holes that allow placement of a vaginal cylinder, available in different sizes to accommodate different vaginal lengths and intrauterine tubes of varying angles and lengths. Additionally, the plates are drilled with holes to introduce straight and angled titanium needles [18]. The plates have three dimples where three A-vitamin pellets are placed. These pellets produce a high signal in both T1 and T2 sequences and are used in the reconstruction process. The needles are reconstructed following their black tunnel signal and tip void. In T1 MRI, the positions can be determined properly but in T2, there is insufficient contrast [18]. Therefore, the depth of each needle must be obtained by measuring the free length with a ruler.

The MRI scans of the patients were acquired with a 1.5 T MRI imager (Optima MR 450w, software version DV24, GE Medical Systems, Milwaukee, Wisconsin, USA). An eight-channel phased array receiver coil was used following standard clinical MRI protocols. Following the GEC-ESTRO recommendations [6,7,8], the acquisition consisted of an axial T2 weighted fast recovery fast spin echo (FRFSE) sequence with the slice thickness reduced to 2 mm. This sequence was used for both delineation and reconstruction. Magnetic resonance imaging acquisition setting details have been described in a publication by Richart et al. [18]. The developed library has been implemented in the Oncentra Brachytherapy TPS, version 4.3.0, with a brachytherapy module that includes a library of rigid applicators. An independent program, the Library Manager Applicator (LMA), was used to add 3D models of the applicators to the Oncentra database.

## Utrecht and Template Benidorm applicators implementation in the TPS library

In the Oncentra TPS (Nucletron, an Elekta company, Elekta AB, Stockholm, Sweden), the input files for the library application manager are a set of Extensible Markup Language (xml) files organized in a hierarchical structure. The main file has a rule.xml extension. In this main file, each applicator, with all its options, is configured for use in Oncentra. The blocks used in this file are separate files that include information about properties of channels, ovoids, etc. These blocks are divided in four kinds of files: tubes, ovoids, cylinders, and fixations. These files contain four subsections: 1) a description of the file, including the part ID and the type; 2) the set of anchor points; 3) the connectors used; 4) information about the surface of the element (called the cursive in Oncentra).

## The Utrecht applicator

In this case, we started from a model provided by Elekta without the interstitial component. The first challenge was to determine distance from the surface of the ovoids of the output points of the needles. We used the technical information provided by Elekta to obtain the coordinates of the output points of the needles in the intrinsic reference system of the ovoids (Figure 1). To determine the coordinates in the reference system of the applicator, we had to find the required translation and a rotation. The translation is given by the tip position of each ovoid tube. To find the rotation, we obtained the plane of each of the ovoid tubes from the data in the file corresponding to the ovoid tube in the center curve section, using the minimum square method. After defining the planes, we had to match the x and z directions in both reference systems.

Once we had the output points, the next step was to create a file corresponding to each needle. A 3D model of each needle was created with FreeCAD (version 0.14, http://www.freecadweb.org/) and open parametric modeler software. By exporting this model to an Wavefront .obj file (obj) and processing it in Excel, we got the cursive section. The connector for the needle in this new file was also obtained using a FreeCAD model. The connectors defined in the ovoid tube file are the outputs points for the ovoid computed in the Utrecht applicator reference system.

## Template Benidorm

The modeling process for TB was different. Because only intrauterine tubes from the vaginal applicator set were included in the Oncentra data base, we had to use FreeCAD to create a new 3D model of the template. Using this program, we translated the real prototype to a vector file and modeled titanium needles, 4 cylinders (45 mm, 80 mm, 100 mm, and 135 mm), and the perineal plates with the A-vitamin pellets (Figure 2). This step gave us the necessary information regarding the skin of the applicator, and provided data we needed for the relative positions of all the parts that configured the applicator, so that the connectors could be created. With all this information, we created different files and their links using techniques described in previous sections.

## Reconstruction procedure

For the Utrecht applicator, the MRI T2 reconstruction process was based on the points that the rigid section and the interstitial part have in common. First, the rigid part was reconstructed using the specific dummies that existed for the tandem and ovoids, which were clearly visible in T2 sequence, together with the cursive of the applicator. These have been described in a previous publication [19] and the dummies are currently provided to users by Elekta. These dummies consist of catheters filled with a saline and iodine mixture. Just water provides sufficient visibility, and the iodine colors the liquid to facilitate checking for bubbles. The distal end of the dummy corresponds with the maximum source-to-indexer distance of the high-dose-rate afterloader. The tip position of both ovoids and the tip position of the intrauterine tandem (MRI markers) are used as anchor points to locate the applicator. Small corrections to better fit the signal void and the MRI markers are made, using the indentations in the cursive of the ovoids and tandem. Unlike tandem and ovoids, this type of dummy is incompatible with plastic needles, due to their narrower diameter. Because the needles are not perfectly rigid, slight deviations in the modeled positions of the needle tips can be present. To account for this, small corrections can be made by rotating the needles at their exit points on the ovoids.

The correct modeling of the intracavitary component gives us the location of the needle output points; these are the exit points at the ovoid’s surface. Combining this information with the free length, enables us to know the complete needle position. In case of TB, once the choice of the needles was made, we entered the configuration of needles and the free length data into a home-made java application (Figure 3) to generate xml files and then imported them to mum source-to-indexer distance of the high-dose-rate afterloader. The tip position of both ovoids and the tip position of the intrauterine tandem (MRI markers) are used as anchor points to locate the applicator. Small corrections to better fit the signal void and the MRI markers are made, using the indentations in the cursive of the ovoids and tandem. Unlike tandem and ovoids, this type of dummy is incompatible with plastic needles, due to their narrower diameter. Because the needles are not perfectly rigid, slight deviations in the modeled positions of the needle tips can be present. To account for this, small corrections can be made by rotating the needles at their exit points on the ovoids.

The correct modeling of the intracavitary component gives us the location of the needle output points; these are the exit points at the ovoid’s surface. Combining this information with the free length, enables us to know the complete needle position. In case of TB, once the choice of the needles was made, we entered the configuration of needles and the free length data into a home-made java application (Figure 3) to generate xml files and then imported them to the LMA from Oncentra. In the LMA, we chose the cylinder and the intrauterine components and then exported that information to Oncentra. After selecting the previously composed model, we located the three pellets in the image to determine the position of the applicator. As in the Utrecht case, we made some small corrections using the cursive data to improve the position of the cylinder and the intrauterine tandem, and verified these changes using the signal void data from the MRI image. Slight deviations from the modeled positions of the needles were corrected as described above with the aim of matching the theoretical position with the black signal on the MRI image. A good match is important because the position of tip of the needle is inter-related to the free-length data (Figure 4).





