### Which are the consequences associated to the uncertainties in reconstruction process? [@tanderup2008]

Las incertidumbres de reconstrucción se pueden dividir en dos categorías: incertidumbres sistemáticas e incertidumbres aleatorias. Las incertidumbres sistemáticas son aquellas que tienen la misma influencia en todas las fracciones de braquiterapia. Ejemplos de ello son las distorsiones en la resonancia magnética y los procedimientos de reconstrucción incorrectos. Las incertidumbres aleatorias son aquellas que difieren entre las sesiones de braquiterapia. Están relacionadas con la visibilidad del aplicador en las imágenes y con la precisión de la fusión de imágenes, si se aplica durante la reconstrucción del aplicador. Las distorsiones en resonancia magnética también pueden aumentar las incertidumbres aleatorias cuando están relacionadas con la interacción específica del paciente con el campo magnético. Las incertidumbres de reconstrucción son generalmente más pronunciadas en la dirección perpendicular a la orientación de las imágenes (dirección longitudinal) debido al gran tamaño de píxel en esta dirección. La resolución limitada reduce la visibilidad del aplicador y las incertidumbres de fusión de imágenes también serán más pronunciadas en esta dirección. Esta dirección se encuentra a lo largo del eje uterino para la imágenes paratransversales (imágenes orientadas según la orientación del aplicador [@dimopoulos2006a]) y a lo largo del eje longitudinal del paciente en caso de imágenes transversales.

Desviaciones en los parámetros DVH: Las desviaciones en los parámetros DVH dependen de la dirección de la incertidumbre de reconstrucción. Los órganos más sensibles son el recto y la vejiga, donde los cambios promedio en los parámetros DVH pueden ser del 5 al 6% por milímetro de desplazamiento del aplicador en la dirección antero-posterior. En otras direcciones y para otros parámetros DVH, las desviaciones promedio son inferiores al 4% por milímetro.

Errores sistemáticos y aleatorios: Los errores sistemáticos en la reconstrucción del aplicador pueden llevar a desviaciones significativas en los parámetros DVH si no se controlan adecuadamente. Por otro lado, los errores aleatorios pueden reducirse mediante la optimización del procedimiento de imagen y el uso de un grosor de corte lo más pequeño posible.

Impacto en la dosis entregada: Las incertidumbres en la reconstrucción pueden tener un impacto en la dosis entregada a los tejidos. Se ha establecido un límite del 10% para la desviación de los parámetros DVH con respecto al valor esperado. De esta manera, se busca asegurar que la dosis entregada sea al menos el 90% de la dosis esperada para las estructuras objetivo y no exceda el 110% de la dosis esperada en los órganos en riesgo.